### ISSUE TITLE
Error when stopping the server

### ISSUE THREAD

**Issue by mcschuetz** [FubarDevelopment/FtpServer#126]
I get the following error:
```
Failed to stop the client connection: The CancellationTokenSource has been disposed.
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at FubarDev.FtpServer.FtpConnection.ConnectionClosingNetworkStreamReader.OnCloseAsync(Exception exception, CancellationToken cancellationToken)
   at FubarDev.FtpServer.Networking.PausableFtpService.StopAsync(CancellationToken cancellationToken)
   at FubarDev.FtpServer.FtpConnection.StopAsync()
```

The crazy thing is that this error occurs in the middle of the night with no access to the server. I can not understand why this occurs.

The target state should actually be that it always runs without pause/stop.

Thanks for help!

**Comment by fubar-coder** [comment]
Hmm, the "middle of the night". Sounds like an internet disconnect from the ISP while a client still has an active connection. Connection loss is something that I need to test.
