### ISSUE TITLE
Provide configurable IP address when using NAT

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/FtpServer#54]
In case of NAT, the local IP address differs from the public IP address. We must provide a way to make this configurable.

**Comment by avonheimburg** [comment]
Already done and already part of pull request #50, called "PasvAddress'.

**Comment by avonheimburg** [comment]
See FtpServerOptions.cs

**Comment by fubar-coder** [comment]
Yes, you're right. It's the `PasvExternalAddress` option. I'll leave this open, because I'd like to change this a little bit to support the special case where a service might have multiple "public" IP addresses (e.g. IPv4, IPv6 and available over multiple network interfaces behind firewalls, etc...)

**Comment by fubar-coder** [comment]
You can find my proposed solution in the `release/3.0` branch. It's not published yet.

The idea is implemented using an `IPasvAddressResolver` service. This service gets the connection and returns `PasvListenerOptions`. This allows the specification of a public IP address and IP port range depending on the local IP address (network interface). This also allows us to return an IPv6 address when the user connects via IPv6.

There is a standard implementation called `SimplePasvAddressResolver` which can be configured using `SimplePasvOptions`.

**Comment by teedty1** [comment]
Whenever I set the PasvAddress all passive traffic stops working in the demo app.  Am I missing something?  Below is my log.  

2019-03-01 22:12:58.1305 INFO  Started listening on 0.0.0.0:21
2019-03-01 22:12:58.1399 TRACE  Background transfer worker starting
Press ENTER/RETURN to close the test application.
2019-03-01 22:12:58.1399 DEBUG  Background transfer worker started.
2019-03-01 22:13:09.9017 INFO  PASV port range set to 57000:57500
2019-03-01 22:13:09.9489 INFO 127.0.0.1:52720 Connected from 127.0.0.1:52720
2019-03-01 22:13:09.9489 TRACE 127.0.0.1:52720 220 FTP Server Ready
2019-03-01 22:13:09.9647 TRACE 127.0.0.1:52720 USER tester
2019-03-01 22:13:09.9647 INFO 127.0.0.1:52720 331 User tester logged in, needs password
2019-03-01 22:13:09.9795 TRACE 127.0.0.1:52720 PASS **************** (password omitted)
2019-03-01 22:13:09.9835 TRACE 127.0.0.1:52720 230 Password ok, FTP server ready
2019-03-01 22:13:09.9835 TRACE 127.0.0.1:52720 OPTS UTF8 ON
2019-03-01 22:13:09.9835 TRACE 127.0.0.1:52720 200 Command okay.
2019-03-01 22:13:10.0019 TRACE 127.0.0.1:52720 PWD
2019-03-01 22:13:10.0019 TRACE 127.0.0.1:52720 257 "/"
2019-03-01 22:13:10.0019 TRACE 127.0.0.1:52720 TYPE I
2019-03-01 22:13:10.0019 TRACE 127.0.0.1:52720 200 Binary transfer mode active.
2019-03-01 22:13:10.0160 TRACE 127.0.0.1:52720 PASV
2019-03-01 22:13:11.9261 TRACE 127.0.0.1:52720 227 Entering Passive Mode (192,168,80,100,223,218).
2019-03-01 22:13:16.9544 TRACE 127.0.0.1:52720 MLSD
2019-03-01 22:13:16.9544 DEBUG 127.0.0.1:52720 150 Opening data connection.
2019-03-01 22:13:17.0133 ERROR 127.0.0.1:52720 Passive connection expected, but none found System.InvalidOperationException: Passive connection expected, but none found
   at FubarDev.FtpServer.FtpConnection.CreateResponseSocket() in C:\temp\FtpServer-master\FtpServer-master\src\FubarDev.FtpServer\FtpConnection.cs:line 208
   at FubarDev.FtpServer.ConnectionExtensions.SendResponseAsync(IFtpConnection connection, Func`2 asyncSendAction, Func`2 createConnectionErrorFunc) in C:\temp\FtpServer-master\FtpServer-master\src\FubarDev.FtpServer.Abstractions\ConnectionExtensions.cs:line 35
2019-03-01 22:13:17.1153 WARN 127.0.0.1:52720 425 Can't open data connection.
