### ISSUE TITLE
FtpServer-3.0 and WinSCP: Status must be Paused, but was ReadyToRun

### ISSUE THREAD

**Issue by avonheimburg** [FubarDevelopment/FtpServer#76]
When connecting to FtpServer-3.0 with WinSCP, we intermittently but frequently get the following error:

```
2019-08-15 13:05:33Z [INF] FtpConnection - Status must be Paused, but was ReadyToRun.
System.InvalidOperationException: Status must be Paused, but was ReadyToRun.
   at FubarDev.FtpServer.Networking.PausableFtpService.ContinueAsync(CancellationToken cancellationToken)
   at FubarDev.FtpServer.ServerCommandHandlers.ResumeConnectionServerCommandHandler.ExecuteAsync(ResumeConnectionServerCommand command, CancellationToken cancellationToken)
   at FubarDev.FtpServer.FtpConnection.SendResponsesAsync(ChannelReader`1 serverCommandReader, CancellationToken cancellationToken)
```

WinSCP then errors out with `Zeit abgelaufen (Kontrollverbindung)`. This could be related to #75, perhaps?

**Comment by fubar-coder** [comment]
I have problems reproducing this problem. What are you machine specs?

**Comment by fubar-coder** [comment]
Version 3.0.1 should be out soon.
