### ISSUE TITLE
TLS doesn't work in 3.1.1

### ISSUE THREAD

**Issue by jhaygood86** [FubarDevelopment/FtpServer#87]
Using FubarDev.Ftpserver 3.1.1 with FubarDev.FtpServer.AuthTls 1.3.7 doesn't work. It runs, but you can't connect to it. There isn't any erorrs

It works in 3.0.1

Logs from 3.1.1: (Not Working)

`
2019-11-19 15:17:17,295 VATLLXT4LJHAYGO [22] DEBUG FubarDev.FtpServer.FtpConnection - Executing server command "FubarDev.FtpServer.ServerCommands.TlsEnableServerCommand"
2019-11-19 15:17:17,297 VATLLXT4LJHAYGO [22] DEBUG FubarDev.FtpServer.ServerCommandHandlers.TlsEnableServerCommandHandler - Enable SslStream
2019-11-19 15:17:17,299 VATLLXT4LJHAYGO [11] DEBUG FubarDev.FtpServer.FtpConnection - &?????,?z????  :?,???
???+? ???0????/? ? 5?? ? /?? ??? 9?? ? 3??        
           
2019-11-19 15:17:17,325 VATLLXT4LJHAYGO [26] DEBUG FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory - Create SSL stream
2019-11-19 15:17:17,326 VATLLXT4LJHAYGO [26] DEBUG FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory - Authenticate as server
2019-11-19 15:17:17,328 VATLLXT4LJHAYGO [11] DEBUG FubarDev.FtpServer.FtpConnection -    
	       #   3 ? ?  a5??6???<?+???'??}??0OHz??????????YN3H??k!???????/?
2019-11-19 15:17:37,344 VATLLXT4LJHAYGO [33] DEBUG FubarDev.FtpServer.FtpConnection - Stopped reading commands
2019-11-19 15:17:37,384 VATLLXT4LJHAYGO [11] DEBUG FubarDev.FtpServer.FtpConnection - StopAsync called
2019-11-19 15:17:37,472 VATLLXT4LJHAYGO [10] ERROR FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory - Authentication failed because the remote party has closed the transport stream.
System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsServer(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory.<WrapStreamAsync>d__2.MoveNext()
`

Logs from 3.0.1 (Working)

`2019-11-19 15:26:14,822 VATLLXT4LJHAYGO [10] DEBUG FubarDev.FtpServer.ServerCommandHandlers.SendResponseServerCommandHandler - 234 Enabling TLS Connection
2019-11-19 15:26:14,823 VATLLXT4LJHAYGO [10] DEBUG FubarDev.FtpServer.FtpConnection - Executing server command "FubarDev.FtpServer.ServerCommands.TlsEnableServerCommand"
2019-11-19 15:26:14,842 VATLLXT4LJHAYGO [10] DEBUG FubarDev.FtpServer.ServerCommandHandlers.TlsEnableServerCommandHandler - Enable SslStream
2019-11-19 15:26:14,917 VATLLXT4LJHAYGO [11] DEBUG FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory - Create SSL stream
2019-11-19 15:26:14,919 VATLLXT4LJHAYGO [11] DEBUG FubarDev.FtpServer.Authentication.DefaultSslStreamWrapperFactory - Authenticate as server
2019-11-19 15:26:15,021 VATLLXT4LJHAYGO [12] DEBUG FubarDev.FtpServer.ServerCommandHandlers.TlsEnableServerCommandHandler - Set close function
2019-11-19 15:26:15,022 VATLLXT4LJHAYGO [12] DEBUG FubarDev.FtpServer.FtpConnection - Executing server command "FubarDev.FtpServer.ServerCommands.ResumeConnectionServerCommand"`

**Comment by fubar-coder** [comment]
It may be a bug, I'll look into it. Just for your information: `FubarDev.FtpServer.AuthTls` is an old package and isn't needed since 2.x.

**Comment by jhaygood86** [comment]
I removed that package. It wasn't actually being referenced.

**Comment by fubar-coder** [comment]
Bug should be fixed in 3.1.2-beta.5 on nuget.org, please leave a note when you've verified that it works now and I'll deploy a 3.1.2 on nuget.org.

Please wait ca. 1 hour before you try to update.
